#!/bin/bash
#
# 1. Mount the official ISO as a directory
#    mount -o loop /tmp/linux-install.iso /mnt/linux
# 2. Copy the contents to a working directory
#    cd /mnt/
#    tar -cvf - linux | (cd /var/tmp/ && tar -xf - )
# 3. Make your changes in /var/tmp/linux directory
# 4. Repackage the directory into a new ISO file
#    cd /var/tmp/linux
#     mkisofs -o ../your-new.iso -b isolinux/isolinux.bin -c isolinux/boot.cat 
#        -no-emul-boot -boot-load-size 4 -boot-info-table -J -R -V Your Disk Name Here
#
# https://www.tldp.org/HOWTO/Bootdisk-HOWTO/cd-roms.html
# https://toggen.com.au/faqs/mine/windows_boot_cd/addbootsectortocd.html
# https://arstechnica.com/civis/viewtopic.php?t=308491
# https://userpages.uni-koblenz.de/~krienke/ftp/noarch/geteltorito/geteltorito/geteltorito.pl
#
# http://www.voidcn.com/article/p-movbdrjl-bcz.html
# mkisofs -udf -b BOOT/BOOTSECT.BIN -no-emul-boot -c BOOT/boot.catalog -o ../winxp_en_sp4.iso \
#	-boot-load-size 4 -no-iso-translate -iso-level 2 -D -V "WINXPVM" -relaxed-filenames -l -N .

mkisofs -b BOOT/BOOTSECT.BIN -no-emul-boot -c BOOT/BOOT.CAT -o ../winxp_en_sp4.iso \
	-no-iso-translate -iso-level 2 -D -V "WINXPVM" -relaxed-filenames -l -N .

